ads-github-fetch-all-upstreams (wip): parse HTTP response code for resp to initial pagination req

diff --git a/src/main/bash/bin/ads-github-fetch-all-upstreams b/src/main/bash/bin/ads-github-fetch-all-upstreams
--- a/src/main/bash/bin/ads-github-fetch-all-upstreams
+++ b/src/main/bash/bin/ads-github-fetch-all-upstreams
@@ -128,9 +128,12 @@ declare -a NEEDED_EXTERNAL_PROGS=(
     cat
     curl
     expr
+    head
     jq
     git
     git-hub
+    sed
+    tr
 )
 
 
@@ -370,6 +373,12 @@ MY_GITHUB_REPOS_URL="${gl_const_github_api_base_url}user/repos?per_page=100"
 
 declare -a MY_CURL_OPTS=()
 
+# This disables output of curl's progress meter /and/ output of error messages...
+MY_CURL_OPTS+=( '--silent' )
+# ...but this re-enables output of the error messages.
+MY_CURL_OPTS+=( '--show-error' )
+
+
 # Force use of TLS 1.2. Writing in 2016, all previous versions are known to be
 # broken and susceptible to known attacks. Note that the '--tlsv1.2' option
 # was added in curl 7.34.0
@@ -421,6 +430,155 @@ MY_CURL_OPTS+=( "${gl_const_http_accept_github_version}" )
 # ...
 # Link: <https://api.github.com/user/repos?per_page=100&page=2>; rel="next", <https://api.github.com/user/repos?per_page=100&page=4>; rel="last"
 
+MY_TOTAL_REPO_PAGES=0
+t_keep_going=true
+while $t_keep_going; do
+    t_head_response=$( curl "${MY_CURL_OPTS[@]}" \
+                            --head               \
+                            "${MY_GITHUB_REPOS_URL}" \
+                       | tr -d '\r' )
+
+    if test $? -ne 0; then
+        # Hopefully curl printed something meaningful to stderr here...
+        printf "${PROG} (error): was unable to obtain pagination info for repos; bailing out\n" 1>&2
+        exit 1
+    fi
+
+    # From RFC 7230:
+    #
+    #     3.1.2.  Status Line
+    #
+    #        The first line of a response message is the status-line, consisting
+    #        of the protocol version, a space (SP), the status code, another
+    #        space, a possibly empty textual phrase describing the status code,
+    #        and ending with CRLF.
+    #
+    #          status-line = HTTP-version SP status-code SP reason-phrase CRLF
+    #
+    #        The status-code element is a 3-digit integer code describing the
+    #        result of the server's attempt to understand and satisfy the client's
+    #        corresponding request.  The rest of the response message is to be
+    #        interpreted in light of the semantics defined for that status code.
+    #        See Section 6 of [RFC7231] for information about the semantics of
+    #        status codes, including the classes of status code (indicated by the
+    #        first digit), the status codes defined by this specification,
+    #        considerations for the definition of new status codes, and the IANA
+    #        registry.
+    #
+    #          status-code    = 3DIGIT
+    #
+    #        The reason-phrase element exists for the sole purpose of providing a
+    #        textual description associated with the numeric status code, mostly
+    #        out of deference to earlier Internet application protocols that were
+    #        more frequently used with interactive text clients.  A client SHOULD
+    #        ignore the reason-phrase content.
+    #
+    #          reason-phrase  = *( HTAB / SP / VCHAR / obs-text )
+    #
+    # Note that we're following Postel's Prescription to an extent in being
+    # lenient about whether or not there is more than a single whitespace
+    # token between fields.
+    #
+    t_http_head_stat_and_label=$(echo "${t_head_response}" | head -n 1 | sed -n -e '/^HTTP[/]/ { s#^HTTP/[^[:space:]]\{1,\}[[:space:]]\{1,\}\([[:digit:]]\{3\}[[:space:]]\{1,\}.*\)#\1#p;q }')
+    if test -z "${t_http_head_stat_and_label}"; then
+        printf "${PROG} (error): was unable to extract HTTP status code from responses; bailing out\n    Full HTTP response headers:\n%s\n" \
+               "$(echo "${t_head_response}" | sed -e 's/^/        /')" 1>&2
+        exit 1
+    fi
+
+    if $DEBUGGING; then
+        printf "${PROG} (debug): HTTP status and label for pagination info: %s\n" "${t_http_head_stat_and_label}" 1>&2
+    fi
+
+    t_http_head_stat=$(  echo "${t_http_head_stat_and_label}" | sed -e 's#^\([[:digit:]]\{3\}\)[[:space:]]\{1,\}.*#\1#')
+    t_http_head_label=$( echo "${t_http_head_stat_and_label}" | sed -e 's#^[[:digit:]]\{3\}[[:space:]]\{1,\}\([[:space:][:alnum:][:punct:]]*\)$#\1#')
+
+    if $DEBUGGING; then
+        printf "${PROG} (debug): HTTP status for pagination info: %s\n" "${t_http_head_stat}"  1>&2
+        printf "${PROG} (debug): HTTP label for pagination info: %s\n"  "${t_http_head_label}" 1>&2
+    fi
+
+    if test -z "${t_http_head_stat}"; then
+        printf "${PROG} (error): was unable to determine HTTP status code of pagination info request for repo; bailing out\n" 1>&2
+        exit 1
+    fi
+
+    # Slice off leading zeros in bogon HTTP response code. Belt AND suspenders...
+    #
+    t_http_head_stat=$((10#$t_http_head_stat))
+
+    if test $t_http_head_stat -lt 100; then
+        # We'll include the full response line to help in troubleshooting. In
+        # the worst case scenario we will learn that we mis-parsed it somehow,
+        # which is a really a win in the long term.
+        printf "${PROG} (error): received bogon HTTP status line with response code less than 100 (\"%s\"); bailing out\n" "${t_http_head_stat_and_label}" 1>&2
+        exit 1
+    fi
+
+    # Oh hell, if we're gonna check the lower bound, then we're boning it if
+    # we don't also check the upper bound...
+    if test $t_http_head_stat -gt 599; then
+        printf "${PROG} (error): received bogon HTTP status line with response code greater than 599 (\"%s\"); bailing out\n" "${t_http_head_stat_and_label}" 1>&2
+        exit 1
+    fi
+
+    # So we know that the HTTP status code is somewhere between 100 and 599...
+
+    if test $t_http_head_stat -ge 100 \
+    && test $t_http_head_stat -lt 200; then
+        printf "${PROG} (error): program does not directly grok HTTP 1xx \"Informational\" status codes; bailing out\n    Full HTTP response headers:\n%n\n" \
+               "$(echo "${t_head_response}" | sed -e 's/^/        /')" 1>&2
+        exit 1
+    fi
+
+    if test $t_http_head_stat -ge 300 \
+    && test $t_http_head_stat -lt 400; then
+        printf "${PROG} (error): program does not directly grok HTTP 3xx \"Redirection\" status codes; bailing out\n"\
+"    If you encounter this error, please submit a bug report; real-world need is likely to get it fixed.\n"\
+"    Full HTTP response headers:\n%n\n" \
+               "$(echo "${t_head_response}" | sed -e 's/^/        /')" 1>&2
+        exit 1
+    fi
+
+    if test $t_http_head_stat -ge 400 \
+    && test $t_http_head_stat -lt 500; then
+        printf "${PROG} (error): program received a HTTP 4xx \"Client Error\" status codes; bailing out\n"\
+"    If you encounter this error, please submit a bug report; it suggests there is a problem with the\n"\
+"    way in which the program is formulating requests to the upstream GitHub service.\n"\
+"    Full HTTP response headers:\n%n\n" \
+               "$(echo "${t_head_response}" | sed -e 's/^/        /')" 1>&2
+        exit 1
+    fi
+
+    if test $t_http_head_stat -ge 500 \
+    && test $t_http_head_stat -lt 600; then
+        printf "${PROG} (error): program received a HTTP 5xx \"Server Error\" status codes; bailing out\n"\
+"    If you encounter this error, it suggests there is a problem with the upstream GitHub service;\n"\
+"    please wait a while and try your request later.\n"\
+"    Full HTTP response headers:\n%n\n" \
+               "$(echo "${t_head_response}" | sed -e 's/^/        /')" 1>&2
+        exit 1
+    fi
+
+    # Internal sanity check
+    if test $t_http_head_stat -ge 200 \
+    && test $t_http_head_stat -lt 300; then :; else
+        printf "${PROG} (bug): internal check failed. Expected that we received a 2xx \"Successful\" HTTP status code, but really have: \"%s\"; bailing out.\n"\
+"    If you encounter this error, there is a serious bug with this program; please submit a bug report.\n"\
+"    Full HTTP response headers:\n%n\n" \
+               "$(echo "${t_head_response}" | sed -e 's/^/        /')" 1>&2
+        exit 1
+    fi
+
+
+#FIXME: working here
+#       [ ] Push above mumbo jumbo into a function
+#       [ ] Extract 'Link: ' header pagination info
+
+
+    t_keep_going=false
+
+done
 
 # repo_name:repo_full_name:default_branch
 #
@@ -432,13 +590,8 @@ MY_CURL_OPTS+=( "${gl_const_http_accept_github_version}" )
 #     ac-nrepl:salewski/ac-nrepl:master
 
 REPO_DATA_LINES=''
-t_keep_going=true
-while $t_keep_going; do
-    curl "${MY_CURL_OPTS[@]}" \
-         --head               \
-         "${MY_GITHUB_REPOS_URL}"
-done
 
+REPO_DATA_LINES=''
 
 
 # $ jq -r '.[] | .name + ":" + .full_name + ":" + .default_branch' < all-repos-per_page-105-001.js | head
