issue #81: [3/4]: cache: limit background procs based on cpu count
When retrieving pages of data (from the remote GitHub site) for a
path that represents a "paged collection", the ads-github-cache
program now limits the number of subshell subprocesses it will spawn
at any one moment (rather than just spawning a subshell for all
pages all at the same time).

This change limits the number based on two criteria:

    1. The number of available CPUs found. The limit imposed
       is (arbitrarily) twice this number, recognizing that even on
       a single-CPU machine it is likely more efficient to have at
       least two concurrent HTTP requests to the GitHub API (since
       there will be a fair amount of time just waiting for the
       response to come back).

       Note that the "number of available CPUs" is determined using
       the recently added 'ads-github-nproc' program.

    2. A hard cap of 20 outstanding subshell processes. This is just
       an arbitrarily chosen number that is intended to keep the
       program from making an overly-large number of concurrent
       requests to the GitHub API, which would otherwise be the case
       with just (1) above on a machine with a large number of
       CPUs.

Note that a future commit will allow the user to specify the number
directly, so in the end there will be three criteria controlling
this behavior.

Signed-off-by: Alan D. Salewski <ads@salewski.email>

diff --git a/src/main/bash/bin/ads-github-cache.in b/src/main/bash/bin/ads-github-cache.in
--- a/src/main/bash/bin/ads-github-cache.in
+++ b/src/main/bash/bin/ads-github-cache.in
@@ -148,6 +148,19 @@ BE_VERBOSE=false   # enable with one '-v' (--verbose) opt
 DEBUGGING=false    # enable with two '-v' (--verbose) opts
 TRACING=false      # enable with three or more '-v' (--verbose) opts
 
+# Limits the number of background processes that will be created at one time
+# in order to obtain, concurrently, data to cache.
+#
+# Yes, this is arbitrary, but we do not want to hammer on the remote GitHub v3
+# API endpoints. On a large machine with, say 128 CPU cores, we would not want
+# to create 128 API requests at the same time.
+#
+# We may lower this number based on the number of CPUs we see on the machine,
+# but we will never raise it above this default value.
+#
+declare MAX_BG_PROCS=20
+
+
 # Folks using GitHub Enterprise might access their API at a different
 # location, so we parameterize the base URL for the GitHub API. MAKE SURE THIS
 # URL INDICATES HTTPS (not just HTTP -- you do not want your HTTP Basic Auth
@@ -434,6 +447,8 @@ t_p2=$("${BASENAME_PROG}" "$("${DIRNAME_PROG}" "${t_rp}")") || exit 1
 t_p3=$("${BASENAME_PROG}" "$("${DIRNAME_PROG}" "$("${DIRNAME_PROG}" "${t_rp}")")") || exit 1
 t_p4=$("${BASENAME_PROG}" "$("${DIRNAME_PROG}" "$("${DIRNAME_PROG}" "$("${DIRNAME_PROG}" "${t_rp}")")")") || exit 1
 
+AGH_NPROC_PROG="${t_script_dir}/ads-github-nproc"
+
 # The non-bash-based tools (e.g., those that are Perl- or Rust-based) may or
 # may not be in the same directory, depending on whether or not we are running
 # in-tree.
@@ -461,6 +476,7 @@ fi
 
 declare -a NEEDED_INTERNAL_PROGS=(
     "${AGH_NORMALIZE_URL_PROG}"
+    "${AGH_NPROC_PROG}"
     "${PARSE_NETRC_PROG}"
 )
 for int_tool in "${NEEDED_INTERNAL_PROGS[@]}"; do
@@ -521,6 +537,40 @@ trap 'printf "$PROG (warn): QUIT signal caught; bailing out\n" 1>&2; f_cleanup_a
 trap 'printf "$PROG (warn): TERM signal caught; bailing out\n" 1>&2; f_cleanup_and_die' TERM
 
 trap 'f_cleanup' EXIT
+
+
+MY_CPU_COUNT=$("${AGH_NPROC_PROG}")
+if test $? -ne 0 \
+|| test -z "${MY_CPU_COUNT}" \
+|| ! [[ "${MY_CPU_COUNT}" =~ $RE_ALL_DIGITS ]] \
+|| test "${MY_CPU_COUNT}" -lt 1; then
+    printf "${PROG} (warning): was unable to determine the number of CPUs; assuming 1\n" 1>&2
+    MY_CPU_COUNT=1
+    # Keep going...
+fi
+declare -r -i MY_CPU_COUNT
+
+# Maybe adjust downward $MAX_BG_PROCS
+#
+if test $MY_CPU_COUNT -gt $MAX_BG_PROCS; then
+    # Machine has large number of CPUs -- more than we would want to use for
+    # processes simultaneously hitting the remote GitHub v3 endpoint. Just
+    # stick with our arbitrary (but reasonable) max.
+    #
+    : $PROG \(trace: $LINENO\): Found $MY_CPU_COUNT CPUs. Will cap max bg procs at the default max: $MAX_BG_PROCS
+else
+    # We'll limit the max number of background processes spawned to retrieve
+    # cache data to two times the number of found CPUs (as long as that number
+    # is still below our default value for $MAX_BG_PROCS). Even a single-core
+    # CPU can usefully have multiple requests outstanding (since there will be
+    # a fair amount of just waiting for the response).
+    t_two_times=$(( 2 * MY_CPU_COUNT ))
+    if test $t_two_times -lt $MAX_BG_PROCS; then
+        : $PROG \(trace: $LINENO\): Found $MY_CPU_COUNT CPUs. Will cap max bg procs at: $t_two_times
+        MAX_BG_PROCS=$t_two_times
+    fi
+    unset t_two_times
+fi
 
 
 # It is possible that the local Unix user has more than one GitHub account
@@ -2777,6 +2827,10 @@ f_get_one_validated_colmeta_or_die () {
 
     local t_http_code
     local t_estat
+    if $BE_VERBOSE; then
+        printf "${PROG} (info): making HEAD request for \"%s\"\n" \
+               "${__t_pqf}" 1>&2
+    fi
     t_http_code=$( "${CURL_PROG}" "${MY_CURL_OPTS[@]}" "${t_url_plus_paging}")
     t_estat=$?
     if test ${t_estat} -ne 0; then
@@ -3082,8 +3136,18 @@ f_get_one_collection_or_die () {
 
     local -A t_bg_procs=()
 
-    this_page=0
-    while test ${this_page} -lt ${t_last_page_number}; do
+    # Retrieve pages of data in concurrent background processes. Note that we
+    # enforce limits to the number of background processes that we will make
+    # at any one time. We do not just want to use all available CPUs (if the
+    # number of available CPUs is high), since we are hitting an external
+    # site's API.
+
+    local t_was_bg_err=false
+    local this_page=0
+    local t_rtn_from_bg
+    while test ${this_page} -lt ${t_last_page_number} \
+       && ! $t_was_bg_err; do
+
         (( ++this_page ))
 
         if $BE_VERBOSE; then
@@ -3101,9 +3165,52 @@ f_get_one_collection_or_die () {
         TRACING=$TRACING       \
           f_perform_do_get_one_or_die "${t_url_plus_paging}" &
         t_bg_pid_to_pagenum[$!]="${this_page}"  # capture pid of background process so we can later 'wait' on it
+
+        while test ${#t_bg_pid_to_pagenum[@]} -eq $MAX_BG_PROCS; do
+            # We have hit our limit for the maximum number of background
+            # processes that we want to have concurrently retrieving pages of
+            # data from the GitHub v3 endpoint. We'll loop waiting for one or
+            # more of them to complete before launching any additional
+            # requests.
+
+            for one_pid in "${!t_bg_pid_to_pagenum[@]}"; do
+                # Suppress stderr to avoid messages such as:
+                #     kill: (17163) - No such process
+                if builtin kill -n 0 "${one_pid}" 2>/dev/null ; then
+                    : $PROG \(trace: $LINENO\): fn ${FUNCNAME}: subprocess with pid $one_pid is still running
+                else
+                    wait ${one_pid}
+                    t_rtn_from_bg=$?
+                    if test ${t_rtn_from_bg} -ne 0; then
+                        t_was_bg_err=true
+                        printf "${PROG} (error): \"paged collection\" %s: was error requesting page %s of %s (page size: %s)\n" \
+                               "${__t_pqf}"   \
+                               "${t_bg_pid_to_pagenum[${one_pid}]}" \
+                               "${t_last_page_number}" \
+                               "${gl_const_per_page_size}" 1>&2
+                        # keep going...
+
+                        # XXX: We could tear-down (kill) the rest of the
+                        #      background processes at this point, too, since
+                        #      a single failure causes us to discard the work
+                        #      from all of them, anyway. For now, we simply
+                        #      avoid spawing additional background processes
+                        #      to fetch additional pages when we detect that
+                        #      one has failed, but we we still just wait for
+                        #      the rest to run their course.
+                    fi
+                    unset t_bg_pid_to_pagenum[${one_pid}]
+                fi
+            done
+            if test ${#t_bg_pid_to_pagenum[@]} -eq $MAX_BG_PROCS; then
+                # None of the outstanding requests has yet completed. We sleep
+                # for a short period of time and then check on them again.
+                "${SLEEP_PROG}" '.5'
+            fi
+        done
     done
 
-    local t_was_err=false
+
     while test ${#t_bg_pid_to_pagenum[@]} -gt 0; do
         for one_pid in "${!t_bg_pid_to_pagenum[@]}"; do
             # Suppress stderr to avoid messages such as:
@@ -3112,9 +3219,9 @@ f_get_one_collection_or_die () {
                 : $PROG \(trace: $LINENO\): fn ${FUNCNAME}: subprocess with pid $one_pid is still running
             else
                 wait ${one_pid}
-                t_rtn=$?
-                if test ${t_rtn} -ne 0; then
-                    t_was_err=true
+                t_rtn_from_bg=$?
+                if test ${t_rtn_from_bg} -ne 0; then
+                    t_was_bg_err=true
                     printf "${PROG} (error): \"paged collection\" %s: was error requesting page %s of %s (page size: %s)\n" \
                            "${__t_pqf}"   \
                            "${t_bg_pid_to_pagenum[${one_pid}]}" \
@@ -3130,7 +3237,7 @@ f_get_one_collection_or_die () {
         fi
     done
 
-    if $t_was_err; then
+    if $t_was_bg_err; then
         # More specific error messages should have been printed above, so this
         # more general message is sufficient here. The important thing is that
         # we exit with an error status if something went wrong.
