fixes #19 (ads-github-merge-all-upstreams): avoid using 'git branch' porcelain command
Replaced three invocations of the git porcelain command 'git branch' with (as
appropriate) invocations of git plumbing commands:
```
    git symbolic-ref --short --quiet HEAD
```
or:
```
    git for-each-ref --format='%(refname:short)' 'refs/heads/'
```
or:
```
    git for-each-ref --format='%(refname:short)' 'refs/remotes/upstream/'
```

These changes also have the nice side effect of using one fewer program in two
of our shell pipeline invocations.

diff --git a/src/main/bash/bin/ads-github-merge-all-upstreams.in b/src/main/bash/bin/ads-github-merge-all-upstreams.in
--- a/src/main/bash/bin/ads-github-merge-all-upstreams.in
+++ b/src/main/bash/bin/ads-github-merge-all-upstreams.in
@@ -1476,14 +1476,21 @@ while IFS=':' read -r repo_name repo_full_name default_branch is_fork; do
             exit 100  # from subshell; status specific to this condition
         fi
 
-
-        # Recall that the output of 'git branch' shows a '* ' prefix in front
-        # of the branch that is currently checked out. We use to find the name
-        # of the currently checked-out branch.
+        # Find the name of the currently checked-out branch (if any). Note
+        # that we use the plumbing command 'git symbolic-ref' (rather than the
+        # porcelain command 'git branch') for this. See also:
         #
-        t_git_branch_orig=$("${GIT_PROG}" branch | "${SED_PROG}" -n -e 's/^[*][[:space:]]\{1,\}//p')
+        #     * git-symbolic-ref(1)
+        #     * https://github.com/salewski/ads-github-tools/issues/19
+        #
+        t_git_branch_orig=$("${GIT_PROG}" symbolic-ref --short --quiet HEAD)
         if test $? -ne 0; then
-            printf "${PROG} (error): [repo: \"%s\"] was error while attempting to determine currently checked out branch; bailing out\n" \
+            # The most likely cause of the error is that the user is in a
+            # 'detached HEAD' state (as the result of checking out a tag, or
+            # similar). It is not safe for us to checkout some other branch
+            # because the users commits to the detached HEAD (if any) would be
+            # lost.
+            printf "${PROG} (error): [repo: \"%s\"] was error while attempting to determine currently checked out branch (detached HEAD?); bailing out\n" \
                    "${repo_name}" 1>&2
             exit 1
         fi
@@ -1493,7 +1500,7 @@ while IFS=':' read -r repo_name repo_full_name default_branch is_fork; do
         # copy for both the local repo and the upstream remote (it could have
         # been deleted, or the repo could otherwise be corrupted)
         declare -a t_pipestatus_hold
-        "${GIT_PROG}" branch | "${SED_PROG}" -e 's/^[*][[:space:]]\{1,\}//' | "${GREP_PROG}" -q -F --word-regexp --max-count=1 "${default_branch}"
+        "${GIT_PROG}" for-each-ref --format='%(refname:short)' 'refs/heads/' | "${GREP_PROG}" -q -F --word-regexp --max-count=1 "${default_branch}"
         t_pipestatus_hold=( ${PIPESTATUS[@]} )                                                                
         if test "${t_pipestatus_hold[0]}" -eq 0 \
         && test "${t_pipestatus_hold[1]}" -eq 0; then
@@ -1513,25 +1520,23 @@ while IFS=':' read -r repo_name repo_full_name default_branch is_fork; do
             exit 1  # from subshell
         fi
         #
-        "${GIT_PROG}" branch --remotes | "${SED_PROG}" -e 's/^[[:space:]]\{1,\}//' | "${GREP_PROG}" -q -F --word-regexp --max-count=1 "upstream/${default_branch}"
+        "${GIT_PROG}" for-each-ref --format='%(refname:short)' 'refs/remotes/upstream/' | "${GREP_PROG}" -q -F --word-regexp --max-count=1 "upstream/${default_branch}"
         t_pipestatus_hold=( ${PIPESTATUS[@]} )                                                                
         if { test "${t_pipestatus_hold[0]}" -eq 0 || (( t_pipestatus_hold[0] == ( 128 + gl_const_sigpipe_number ) )); } \
-        && { test "${t_pipestatus_hold[1]}" -eq 0 || (( t_pipestatus_hold[1] == ( 128 + gl_const_sigpipe_number ) )); } \
-        &&   test "${t_pipestatus_hold[2]}" -eq 0; then
+        &&   test "${t_pipestatus_hold[1]}" -eq 0; then
             if $DEBUGGING; then
                 printf "${PROG} (debug): [repo: \"%s\"]: found default branch name (\"%s\") amongst upstream branches\n" "${repo_name}" "${default_branch}" 1>&2
             fi
             # keep going
         elif { test "${t_pipestatus_hold[0]}" -eq 0 || (( t_pipestatus_hold[0] == ( 128 + gl_const_sigpipe_number ) )); } \
-          && { test "${t_pipestatus_hold[1]}" -eq 0 || (( t_pipestatus_hold[1] == ( 128 + gl_const_sigpipe_number ) )); } \
-          &&   test "${t_pipestatus_hold[2]}" -eq 1; then
+          &&   test "${t_pipestatus_hold[1]}" -eq 1; then
 
             printf "${PROG} (error): [repo: \"%s\"]: did not find default branch name (\"%s\") amongst upstream branches; bailing out\n" \
                    "${repo_name}" \
                    "${default_branch}" 1>&2
             exit 1  # from subshell
         else
-            printf "${PROG} (error): [repo: \"%s\"]: was error while reading remote branch names (pipe estats: [0]: %s, [1]: %s, [2]: %s); bailing out\n" "${repo_name}" "${t_pipestatus_hold[@]}" 1>&2
+            printf "${PROG} (error): [repo: \"%s\"]: was error while reading remote branch names (pipe estats: [0]: %s, [1]: %s); bailing out\n" "${repo_name}" "${t_pipestatus_hold[@]}" 1>&2
             exit 1  # from subshell
         fi
 
