issue #81: [4/4]: cache: add -j NUM (--jobs=NUM) option
The 'ads-github-cache' program now accepts a '-j NUM' (--jobs=NUM)
command line option that allows the user to specify the maximum
number of requests to the GitHub API that can be created
simultaneously.

By default (without the command line option), the number is twice
the number of CPUs found to be available at runtime, but with a hard
cap of 20 (to avoid making an excessive number of requests on
machines that happen to have a larger number of CPUs).

If provided, the user-specified number will be used unconditionally,
without any cap (assuming the machine has enough resources
available). Please use this feature responsibly.

Note that values of NUM must be an integer greater than zero (the
program will reject other values and exit with an error status).

If the value 1 is provided for NUM, the effect will be to eliminate
concurrent requests.

Signed-off-by: Alan D. Salewski <ads@salewski.email>

diff --git a/src/main/bash/bin/ads-github-cache.in b/src/main/bash/bin/ads-github-cache.in
--- a/src/main/bash/bin/ads-github-cache.in
+++ b/src/main/bash/bin/ads-github-cache.in
@@ -158,6 +158,7 @@ TRACING=false      # enable with three or more '-v' (--verbose) opts
 # We may lower this number based on the number of CPUs we see on the machine,
 # but we will never raise it above this default value.
 #
+# See also: $USER_SPECIFIED_MAX_BG_PROCS
 declare MAX_BG_PROCS=20
 
 
@@ -552,6 +553,14 @@ declare -r -i MY_CPU_COUNT
 
 # Maybe adjust downward $MAX_BG_PROCS
 #
+# CAREFUL: We're adjusting (possibly) the built-in default limits here, based
+#          on the number of CPUs found to be present at runtime. However, the
+#          user can override the behavior configured here using the '-j NUM'
+#          (--jobs=NUM) command line option, which will be honored "as is" by
+#          this program; the user-specified limit is not subject to the
+#          built-in limit that we are adjusting here. (This is *nix; we will
+#          not second-guess the user.)
+#
 if test $MY_CPU_COUNT -gt $MAX_BG_PROCS; then
     # Machine has large number of CPUs -- more than we would want to use for
     # processes simultaneously hitting the remote GitHub v3 endpoint. Just
@@ -622,6 +631,12 @@ else
     printf "${PROG} (error): was unable to obtain user's GitHub username from netrc; bailing out\n" 1>&2
     exit 1
 fi
+
+
+# If user does not specify the max number of background processes, then
+# $MAX_BG_PROCS will be used (q.v.)
+USER_SPECIFIED_MAX_BG_PROCS=             # set via '-j NUM' ('--jobs=NUM')
+HAVE_USER_SPECIFIED_MAX_BG_PROCS=false
 
 
 # We may or may not write the cache directory beneath this location, depending
@@ -816,6 +831,8 @@ Mandatory arguments to long options are mandatory for short options too.
       --get            Obtain content of specfied URL or path through the cache
       --get-cached     Like '--get', but error out if item is not already present in cache.
                          Avoids updating the cache to obtain the item. Think "offline".
+  -j, --jobs=NUM       Specify the number of concurrent requests against the GitHub API.
+                         Default is 2 * cpu_count, or 20; whichever is lower.
       --update         Update the cache entry for the specified URLs or paths, or all
   -v, --verbose        Print program progress messages on stderr. Specify multiple
                          times to increase verbosity: info, debug, and tracing (set -x)
@@ -837,6 +854,55 @@ There is NO WARRANTY, to the extent permitted by law.
 
 Written by Alan D. Salewski.
 EOF
+}
+
+
+f_set_opt_user_specified_max_bg_procs_or_die() {
+    local __required_count=1
+    if test $# -ne ${__required_count}; then
+        printf "${PROG} (BUG): ${FUNCNAME}() invoked with %d args; exactly %d required; bailing out\n" \
+            $# ${__required_count} 1>&2
+        exit 1
+    fi
+
+    local t_max=$1
+
+    if $HAVE_USER_SPECIFIED_MAX_BG_PROCS; then
+        printf "${PROG} (error): only one '-j NUM' (--jobs=NUM) option may be provided; bailing out\n" 1>&2
+        f_print_help 1>&2
+        exit 1
+    fi
+
+    if test -z "${t_max}"; then
+        printf "${PROG} (error): value provided for max jobs count may not be empty; bailing out\n" 1>&2
+        f_print_help 1>&2
+        exit 1
+    fi
+    if [[ "${t_max}" =~ $RE_BLANK ]]; then
+        printf "${PROG} (error): value provided for max jobs count may not be blank; bailing out\n" 1>&2
+        f_print_help 1>&2
+        exit 1
+    fi
+    if [[ "${t_max}" =~ $RE_ALL_DIGITS ]] \
+    && test "${t_max}" -gt 0; then :; else
+        printf "${PROG} (error): value provided for max jobs count must be an integer greater than zero; bailing out\n" 1>&2
+        f_print_help 1>&2
+        exit 1
+    fi
+
+    USER_SPECIFIED_MAX_BG_PROCS=$t_max
+
+    HAVE_USER_SPECIFIED_MAX_BG_PROCS=true
+
+    declare -g -r USER_SPECIFIED_MAX_BG_PROCS
+    declare -g -r HAVE_USER_SPECIFIED_MAX_BG_PROCS
+
+    if $BE_VERBOSE; then
+        printf "${PROG} (info): will honor user-specified max jobs count: %d\n" \
+               "${USER_SPECIFIED_MAX_BG_PROCS}" 1>&2
+    fi
+
+    return 0  # success
 }
 
 
@@ -3142,6 +3208,13 @@ f_get_one_collection_or_die () {
     # number of available CPUs is high), since we are hitting an external
     # site's API.
 
+    # By default we'll used the baked-in default, but will unquestioningly use
+    # a user-supplied valid, if such a thing was provided.
+    local t_max_bg_procs=$MAX_BG_PROCS
+    if $HAVE_USER_SPECIFIED_MAX_BG_PROCS; then
+        t_max_bg_procs=$USER_SPECIFIED_MAX_BG_PROCS
+    fi
+
     local t_was_bg_err=false
     local this_page=0
     local t_rtn_from_bg
@@ -3166,7 +3239,7 @@ f_get_one_collection_or_die () {
           f_perform_do_get_one_or_die "${t_url_plus_paging}" &
         t_bg_pid_to_pagenum[$!]="${this_page}"  # capture pid of background process so we can later 'wait' on it
 
-        while test ${#t_bg_pid_to_pagenum[@]} -eq $MAX_BG_PROCS; do
+        while test ${#t_bg_pid_to_pagenum[@]} -eq $t_max_bg_procs; do
             # We have hit our limit for the maximum number of background
             # processes that we want to have concurrently retrieving pages of
             # data from the GitHub v3 endpoint. We'll loop waiting for one or
@@ -3202,7 +3275,7 @@ f_get_one_collection_or_die () {
                     unset t_bg_pid_to_pagenum[${one_pid}]
                 fi
             done
-            if test ${#t_bg_pid_to_pagenum[@]} -eq $MAX_BG_PROCS; then
+            if test ${#t_bg_pid_to_pagenum[@]} -eq $t_max_bg_procs; then
                 # None of the outstanding requests has yet completed. We sleep
                 # for a short period of time and then check on them again.
                 "${SLEEP_PROG}" '.5'
@@ -3241,13 +3314,13 @@ f_get_one_collection_or_die () {
         # More specific error messages should have been printed above, so this
         # more general message is sufficient here. The important thing is that
         # we exit with an error status if something went wrong.
-        printf "${PROG} (error): was error while emitting one or more pages for \"paged collection\"\n" \
+        printf "${PROG} (error): was error while emitting one or more pages for \"paged collection\" %s\n" \
                "${__t_pqf}" 1>&2
         exit 1
     fi
 
-    if $DEBUGGING; then
-        printf "${PROG} (debug): all pages for \"paged collection\" successfully emitted\n" \
+    if $BE_VERBOSE; then
+        printf "${PROG} (info): all pages for \"paged collection\" %s successfully emitted\n" \
                "${__t_pqf}" 1>&2
     fi
     return 0
@@ -3749,6 +3822,8 @@ declare -A longopt_spec=(
     ['get']=0
     ['get-cached']=0
 
+    ['jobs']=1      # -j NUM (--jobs=NUM)
+
     ['update']=0
 
     ['verbose']=0   # -v
@@ -3774,7 +3849,7 @@ if test $# -gt 0; then
     # '--', but we still need to deal with the pathological form --=BLAH (no option name,
     # just a value using the equals-sign syntax).
     #
-    while getopts ':-:hVv' opt
+    while getopts ':-:hj:Vv' opt
     do
         : $PROG \(trace: $LINENO\): opt is: $opt
 
@@ -3959,6 +4034,10 @@ if test $# -gt 0; then
 
             'get-cached')
                 f_set_cmd_mode_get_cached_one_or_die '--get-cached'
+                ;;
+
+            'jobs' | 'j')  # -j NUM (--jobs=NUM)
+                f_set_opt_user_specified_max_bg_procs_or_die "${OPTARG}"  # OPTARG should be an integer; will error-out otherwise
                 ;;
 
             'update')
@@ -4337,10 +4416,10 @@ exit 0
 
   ads-github-cache (-h | --help)
   ads-github-cache (-V | --version)
-  ads-github-cache [(-v | --verbose)...] [--cache-dir=DIR] --update [--] [URL_OR_PATH...]
-  ads-github-cache [(-v | --verbose)...] [--cache-dir=DIR] (--get | --get-cached) [--] URL_OR_PATH
-  ads-github-cache [(-v | --verbose)...] [--cache-dir=DIR] --clear  [--] [URL_OR_PATH...]
-  ads-github-cache [(-v | --verbose)...] [--cache-dir=DIR] --clear-all
+  ads-github-cache [OPTION...] --update [--] [URL_OR_PATH...]
+  ads-github-cache [OPTION...] (--get | --get-cached) [--] URL_OR_PATH
+  ads-github-cache [OPTION...] --clear  [--] [URL_OR_PATH...]
+  ads-github-cache [OPTION...] --clear-all
 
 
 =head1 DESCRIPTION
@@ -4428,6 +4507,26 @@ not already present in the cache.
 Avoids updating the cache to obtain the item. The data served may be stale.
 
 No network access is performed.
+
+
+=item -j, --jobs=NUM
+
+Specifies the maximum number of requests to the GitHub API that can be created
+simultaneously.
+
+By default, the number is twice the number of CPUs found to be available at
+runtime, but with a hard cap of 20 (to avoid making an excessive number of
+requests on machines that happen to have a larger number of CPUs).
+
+If provided, the user-specified number will be used unconditionally, without
+any cap (assuming the machine has enough resources available). Please use this
+feature responsibly.
+
+Note that values of NUM must be an integer greater than zero (the program will
+reject other values and exit with an error status).
+
+If the value 1 is provided for NUM, the effect will be to eliminate concurrent
+requests.
 
 
 =item --update
@@ -4927,6 +5026,11 @@ difficult to do accidentally.
 =over 4
 
 =item * L<ads-github-tools(7)>
+
+
+=item * L<ads-github-nproc(1)>
+
+Used to determine the number of CPUs available to the process at runtime.
 
 
 =item * L<ads-github-normalize-url(1)>
