fixes #34: sanity check obtained page count value
This issue was partially fixed by the robustness changes introduced
for issue #33 (see commit 6c6ecb41278e0911dca80), but this changeset
adds a check specific to issue #34 to verify that the obtained page
count value contains all digits. This keeps any emitted error
messages as close as possible to the source of the problem.

diff --git a/src/main/bash/bin/ads-github-fetch-all-upstreams.in b/src/main/bash/bin/ads-github-fetch-all-upstreams.in
--- a/src/main/bash/bin/ads-github-fetch-all-upstreams.in
+++ b/src/main/bash/bin/ads-github-fetch-all-upstreams.in
@@ -848,6 +848,12 @@ f_get_gh_user_repos_pagination_count_or_die () {
         exit 1
     fi
 
+    if test [[ "${t_last_page_number}" =~ $RE_ALL_DIGITS ]]; then :; else
+        printf "${PROG} (error): obtained page counter that contains non-digits (\"%s\"); bailing out\n" \
+               "${t_last_page_number}" 1>&2
+        exit 1
+    fi
+
     printf -v "${__t_out_var_name}" '%s' "${t_last_page_number}"
     return 0  # success
 }
