fixes #63: repo-create: dump http response beneath error message
When attempting to create a new GitHub repo, the service may reject
the API call for any number of reasons. The previous version of the
command simply exited with an error message indicating the HTTP
response code, but in isolation that information is not enough for
the user to understand and address the problem (especially in the
case of 400 errors).

The program has been improved to provide more information to the
user when the repo creation operation fails. It will now dump the
HTTP response content to the screen beneath the error messages,
which is usually a small JSON document that provides more hints
about what the problem was.

diff --git a/src/main/bash/bin/ads-github-repo-create.in b/src/main/bash/bin/ads-github-repo-create.in
--- a/src/main/bash/bin/ads-github-repo-create.in
+++ b/src/main/bash/bin/ads-github-repo-create.in
@@ -1645,8 +1645,15 @@ if test '201' = "${t_http_code}"; then
                "${NEW_REPO_NAME}" 1>&2
     fi
 else
-    printf "${PROG} (error): HTTP response code was: \"%s\"; expected 201 (\"Created\"); bailing out\n" \
-           "${t_http_code}" 1>&2
+    if test -s "${MY_TMP_CURL_OUT_FPATH}"; then
+        printf "${PROG} (error): HTTP response code was: \"%s\"; expected 201 (\"Created\"); bailing out\n"\
+'    Further details may be available in the HTTP response body:\n        %s\n' \
+               "${t_http_code}" \
+               "$("${CAT_PROG}" "${MY_TMP_CURL_OUT_FPATH}")" 1>&2
+    else
+        printf "${PROG} (error): HTTP response code was: \"%s\"; expected 201 (\"Created\"); bailing out\n" \
+               "${t_http_code}" 1>&2
+    fi
     exit 1
 fi
 
