fixes #22 (ads-github-fetch-all-upstreams): add '--missing-only' option
This changeset adds a `'-m'` (`--missing-only`) command line option that
provides a shorthand way of invoking:
```
    $ ads-github-fetch-all-upstreams -c <MISSING_REPO>...
```
while at the same time limiting the program's behavior to only missing
repos. And it does so without the user having to explicitly name (or even
know) the values for each missing repository name.

In this context, a "missing repository" has the same meaning as it does for
the `'-c'` (`--clone-if-missing`) option. That is: any repository from GitHub
where the local git working directory is not present.

The following is the equivalent invocation of the above:
```
    $ ads-github-fetch-all-upstreams -m
```
The semantics of:
```
    $ ads-github-fetch-all-upstreams -m <REPO>...
```
limits the operation of the program to only those explicitly named repos, and
will clone them only if they are missing (that is, the program will not fetch
changes from the corresponding upstream repo when the local repo is already
present; see "Design Notes" section below for more on the rationale for this
behavior). If any of the explicitly named repos are already present, then the
program will print an error message and exit with a non-zero status at the end
(after cloning all of the other explicitly named repos (if any)). This is
intended to make the user aware of any repo names fat-fingered on the command
line.

Note that the `'-m'` (`--missing-only`) option implies
`'-c'`(`--clone-if-missing`), so the `'-c'` in the following is redundant (but
innocuous):
```
    $ ads-github-fetch-all-upstreams -m -c
```
Said another way, the `'--missing-only'` option limits the behavior of the
program to operate /only/ on repos that are missing, so the behavior of the
program when `'--missing-only'` is specified is meaningless unless
`'--clone-if-missing'` were also implied.

Design Notes
------------
The author considered making the semantics of the `'--missing-only'` option,
when provided with explicitly named repo names on the command line, be "fetch
(or clone) these particular repos plus any repos that are missing".

That approach would be consistent with the behavior of:
```
    $ ads-github-fetch-all-upstreams -c <NONMISSING_REPO>...
```
insofar as the repos would be cloned if they were missing, but fetched
otherwise. That idea was ultimately rejected because it would fetch updates
for the repo if its working directory happened to be present. That's not
"missing only" behavior, so would make the behavior of `'--missing-only'` (or
whatever the option would be named) more difficult to explain and
comprehend. It's also not the common case itch being scratched.

This decision does mean, though, that there is currently no way to express
"fetch (or clone) these particular repos plus any repos that are missing" when
one or more of the explicitly named repos is already present, yet still have
the program exit with a zero exit status. This use case can, of course, be
easily accommodated by using two separate invocations of the program:
```
    $ # first clone (as fast as possible) any missing repos...
    $ ads-github-fetch-all-upstreams -m

    $ # ...and then fetch changes for explicitly named repos (note no need for '-c' here)
    $ ads-github-fetch-all-upstreams <REPO>...
```
The second invocation in that example will be an elaborate NOOP when all of
the explicitly named repos were freshly cloned by the first invocation.

If this example represents your common use case and you find this behavior
limiting or otherwise annoying, please contact the author as outlined in the
[BUGS] file.

[BUGS]: https://github.com/salewski/ads-github-tools/blob/master/BUGS

diff --git a/src/main/bash/bin/ads-github-fetch-all-upstreams.in b/src/main/bash/bin/ads-github-fetch-all-upstreams.in
--- a/src/main/bash/bin/ads-github-fetch-all-upstreams.in
+++ b/src/main/bash/bin/ads-github-fetch-all-upstreams.in
@@ -108,6 +108,18 @@ DEBUGGING=false  # debug-level output; override with two '-v' opts
 DO_CLONE_IF_NOT_PRESENT=false
 
 
+# The default behavior of the program is to operate only on working
+# directories that are present ("operate only on these" semantics).
+#
+# Sometimes you want exactly the opposite behavior, though ("fetch all the new
+# stuff" semantics). Our '--missing-only' command line option allows the user
+# to request that behavior.
+#
+# See also: https://github.com/salewski/ads-github-tools/issues/22
+#
+FETCH_ONLY_MISSING=false
+
+
 # It may be the case that we have cloned one of our repositories manually, but
 # for whatever reason have not set up the 'upstream' remote to point to the
 # parent GitHub repository from which ours was cloned.
@@ -257,6 +269,7 @@ Mandatory arguments to long options are mandatory for short options too.
   -h, --help                        Print this help message on stdout
   -V, --version                     Print the version of the program on stdout
   -c, --clone-if-missing            Use git-hub(1) to clone your missing repos from GitHub
+  -m, --missing-only                Operate on (clone) only repos that are missing locally (implies '-c')
   -u, --upstream-remote-if-missing  Setup 'upstream' remote in existing repo working dirs, if missing
 
   -v, --verbose                     Print program progress messages on stderr. Specify multiple
@@ -557,6 +570,7 @@ declare -A longopt_spec=(
     ['version']=0   # -V
 
     ['clone-if-missing']=0            # -c
+    ['missing-only']=0                # -m
     ['upstream-remote-if-missing']=0  # -u
     ['verbose']=0                     # -v
 )
@@ -581,7 +595,7 @@ if test $# -gt 0; then
     # '--', but we still need to deal with the pathological form --=BLAH (no option name,
     # just a value using the equals-sign syntax).
     #
-    while getopts ':-:hcuVv' opt
+    while getopts ':-:hcmuVv' opt
     do
         : $PROG \(trace: $LINENO\): opt is: $opt
 
@@ -733,6 +747,12 @@ if test $# -gt 0; then
 
 
             'c' | 'clone-if-missing' )
+                DO_CLONE_IF_NOT_PRESENT=true
+                ;;
+
+            'm' | 'missing-only')
+                FETCH_ONLY_MISSING=true
+                # The '-m' option implies the '-c' option, so:
                 DO_CLONE_IF_NOT_PRESENT=true
                 ;;
 
@@ -1105,6 +1125,34 @@ while IFS=':' read -r repo_name repo_full_name default_branch is_fork; do
         fi
     fi
 
+    if $FETCH_ONLY_MISSING; then
+
+        if test -d "${repo_name}"; then
+            # We'll treat the presence of a subdirectory with the repo name as "not missing"
+
+            if test "${#EXPLICITLY_REQUESTED_REPOS[@]}" -gt 0; then
+
+                # If we are falling through here then it means that the user
+                # explicitly requested the repo, but it's working directory is
+                # already present. This will ultimately result in the program
+                # exiting with an error status because we are not adding the
+                # repo name to our $PROCESSED_REPOS array. With that being the
+                # case, we'll print the following message as a warning.
+
+                printf "${PROG} (warning): subdirectory exists for repo name \"%s\"; --missing-only specified; skipping\n" \
+                       "${repo_name}" 1>&2
+            else
+
+                if $BE_VERBOSE; then
+                    printf "${PROG} (info): subdirectory exists for repo name \"%s\"; --missing-only specified; skipping (okay)\n" \
+                           "${repo_name}" 1>&2
+                fi
+            fi
+
+            continue
+        fi
+    fi
+
     # If there's a subdirectory beneath the current location with the
     # repository name, then it is probably the git working directory for the
     # project. Note that it is possible to have a project cloned into a
@@ -1116,7 +1164,17 @@ while IFS=':' read -r repo_name repo_full_name default_branch is_fork; do
         if $DO_CLONE_IF_NOT_PRESENT; then
 
             if $BE_VERBOSE; then
-                printf "${PROG} (info): no subdirectory exists for repo name \"%s\"; --clone-if-missing specified, so will clone repo from GitHub\n" "${repo_name}" 1>&2
+                if $FETCH_ONLY_MISSING; then
+                    # The '--missing-only' option implies '--clone-if-missing',
+                    # so we show a slightly different log message to help avoid
+                    # confusion in case the user did not explicitly provide
+                    # '--clone-if-missing' (which would be redundant if '--missing-only'
+                    # was provided).
+                    #
+                    printf "${PROG} (info): no subdirectory exists for repo name \"%s\"; --missing-only specified, so will clone repo from GitHub\n" "${repo_name}" 1>&2
+                else
+                    printf "${PROG} (info): no subdirectory exists for repo name \"%s\"; --clone-if-missing specified, so will clone repo from GitHub\n" "${repo_name}" 1>&2
+                fi
             fi
 
             declare t_v_opts=()
@@ -1501,6 +1559,33 @@ Print the version of the program to stdout and then exit.
 =item -c, --clone-if-missing
 
 Use L<git-hub(1)> to clone your missing repos from GitHub.
+
+
+=item -m, --missing-only
+
+Fetch only repos that are missing locally.
+
+The default behavior of the program is to operate only on working directories
+that are present, or only on those repos that are explicitly named on the
+command line (two different flavors of "operate only on these" semantics).
+
+Sometimes you want exactly the opposite behavior, though ("fetch all the new
+stuff" semantics). Our C<--missing-only> command line option allows the user
+to request that behavior.
+
+This option implies C<--clone-if-missing>) (C<-c>), and effectively provides a
+shorthand way of invoking:
+
+    $ ads-github-fetch-all-upstreams -c <MISSING_REPO>...
+
+without having to explicitly name (or even know) the values for each missing
+repository name.
+
+This behavior is useful, for example, if you have forked a number of different
+GitHub repos and want to have them cloned locally without having to wait for
+the status of all existing repositories to be checked (which can be a long
+time if you have a large number of GitHub repos), and without having to
+explicitly name the missing repos on the command line.
 
 
 =item -u, --upstream-remote-if-missing
